export interface ProcessStep {
  number: number;
  name: string;
  phase: number;
  phaseName: string;
  owner: string;
  prerequisites: number[];
  documents: string[];
  timing: string;
  description: string;
}

export const PHASES = [
  { id: 0, name: "Phase 0: Coordination", color: "bg-sky", textColor: "text-sky", borderColor: "border-sky" },
  { id: 1, name: "Phase 1: Placement", color: "bg-teal", textColor: "text-teal", borderColor: "border-teal" },
  { id: 2, name: "Transition: SMA Setup", color: "bg-amber-500", textColor: "text-amber-600", borderColor: "border-amber-500" },
  { id: 3, name: "Phase 2: Management", color: "bg-navy", textColor: "text-navy", borderColor: "border-navy" },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: 1,
    name: "Client/Advisor Confirmation",
    phase: 0,
    phaseName: "Coordination",
    owner: "JH, the RIA",
    prerequisites: [],
    documents: ["Illustration acceptance", "Client confirmation letter"],
    timing: "Initial",
    description: "Confirm client and all advisors want to move forward. Obtain illustration acceptance and alignment from all parties.",
  },
  {
    number: 2,
    name: "Documentation Gathering",
    phase: 0,
    phaseName: "Coordination",
    owner: "JH, the RIA",
    prerequisites: [],
    documents: ["Client ID", "Address verification", "Trust documents", "LLC membership agreement", "Source of funds statement", "KYC/AML documentation"],
    timing: "Early",
    description: "Gather all required data and documents including identification, entity documents, and KYC/AML materials.",
  },
  {
    number: 3,
    name: "Discretionary Management Agreement",
    phase: 0,
    phaseName: "Coordination",
    owner: "JH, the RIA, Carrier A",
    prerequisites: [],
    documents: ["Discretionary account agreement", "No client control document"],
    timing: "Immediate Priority",
    description: "Ensure the RIA has approved the discretionary account agreement and 'no client control' document with Carrier A.",
  },
  {
    number: 4,
    name: "Account Opening Plan",
    phase: 0,
    phaseName: "Coordination",
    owner: "JH, Structures Partner",
    prerequisites: [],
    documents: ["Account structure requirements", "BNY Mellon capabilities confirmation"],
    timing: "Immediate Priority",
    description: "Build comprehensive account opening plan. Define structure requirements, confirm BNY Mellon capabilities, plan BNYM feed integration.",
  },
  {
    number: 5,
    name: "Secure Data Link",
    phase: 1,
    phaseName: "Placement",
    owner: "Structures Partner, Carrier A",
    prerequisites: [],
    documents: ["Encrypted data transfer pipeline", "Due diligence materials"],
    timing: "1-2 days",
    description: "Establish secure data pipeline and upload all due diligence materials to the carrier's secure portal.",
  },
  {
    number: 6,
    name: "Prepare Application Package",
    phase: 1,
    phaseName: "Placement",
    owner: "Structures Partner, JH",
    prerequisites: [],
    documents: ["Annuity application", "DocuSign package", "Supporting documents"],
    timing: "2-3 days",
    description: "Prepare complete DocuSign package with annuity application and all supporting documents. JH and the carrier contact are final routing stops.",
  },
  {
    number: 7,
    name: "Client Signs",
    phase: 1,
    phaseName: "Placement",
    owner: "Structures Partner",
    prerequisites: [6],
    documents: ["Signed application", "PR counsel review"],
    timing: "1-2 days",
    description: "Client executes DocuSign package. Workflow: Client signs → PR counsel review → Structures Partner oversight → Carrier A.",
  },
  {
    number: 8,
    name: "Carrier Compliance Approval",
    phase: 1,
    phaseName: "Placement",
    owner: "Carrier A",
    prerequisites: [5, 7],
    documents: ["Compliance review documentation"],
    timing: "1-3 days",
    description: "Full compliance review by Carrier A. Verification of all documentation. Case cleared for policy placement.",
  },
  {
    number: 9,
    name: "Open Custodian Account",
    phase: 2,
    phaseName: "SMA Setup",
    owner: "Carrier A",
    prerequisites: [5, 7],
    documents: ["Account-opening documents", "BNY Mellon setup"],
    timing: "Post-compliance",
    description: "Carrier A opens policy account at BNY Mellon. Execute account-opening documents, establish BNYM feeds, configure access.",
  },
  {
    number: 10,
    name: "Execute Discretionary Agreements",
    phase: 2,
    phaseName: "SMA Setup",
    owner: "Carrier A, the RIA",
    prerequisites: [9],
    documents: ["Discretionary management agreement (signed)", "No client control affirmation"],
    timing: "Post-account opening",
    description: "the carrier contact signs discretionary management agreement. the RIA signs 'no client control' affirmation. Discretionary management in force.",
  },
  {
    number: 11,
    name: "Greenlight to Fund",
    phase: 2,
    phaseName: "SMA Setup",
    owner: "Carrier A, the RIA",
    prerequisites: [8, 9, 10],
    documents: ["Funding approval", "Wiring instructions"],
    timing: "Post-agreements",
    description: "Issue approval to fund. Send wiring instructions to the RIA and JH. Wire initiated.",
  },
  {
    number: 12,
    name: "Funds Received",
    phase: 2,
    phaseName: "SMA Setup",
    owner: "Carrier A",
    prerequisites: [11],
    documents: ["Wire confirmation", "Fund receipt"],
    timing: "1-2 days",
    description: "Client → AIBC (Carrier A bank) → Carrier A retains admin charges → BNY Mellon account. Funds fully available for investment.",
  },
  {
    number: 13,
    name: "Portfolio Allocation",
    phase: 3,
    phaseName: "Management",
    owner: "the RIA, Carrier B",
    prerequisites: [12],
    documents: ["Investment allocation orders", "817(h) compliance verification"],
    timing: "Post-funding",
    description: "the RIA invests assets at BNY Mellon across the fund lineup. Must maintain 817(h) diversification and no-client-control. Adequate cash for annual fees.",
  },
  {
    number: 14,
    name: "Policy Delivery",
    phase: 3,
    phaseName: "Management",
    owner: "Carrier A, the RIA",
    prerequisites: [12],
    documents: ["PDF policy document"],
    timing: "Post-funding",
    description: "Carrier A issues PDF policy document. Delivered: the carrier contact → the RIA → Client.",
  },
  {
    number: 15,
    name: "Compensation Finalized",
    phase: 3,
    phaseName: "Management",
    owner: "Carrier A",
    prerequisites: [12],
    documents: ["Compensation statement"],
    timing: "Post-funding",
    description: "Issue compensation per agreement. Process broker dealer commission if applicable. All compensation paid per terms.",
  },
];
